# SPDX-FileCopyrightText: 2024 Adam Twardoch <adam+github@twardoch.com>
#
# SPDX-License-Identifier: MIT

"""
LLM integration for twat.
"""

from __future__ import annotations

try:
    from .__version__ import __version__
except ImportError:
    # Package not installed, or __version__.py not generated by hatch-vcs
    # This is a fallback for development mode when running from source
    # without a proper build/install that generates __version__.py.
    # It's also useful if someone copies the source code without build metadata.
    __version__ = "0.0.0.dev0+unknown" # Placeholder version

# Expose main functionalities if any, e.g.:
# from .twat_llm import process_data, ActionConfig, PersonEnrichmentParams, WebSearchParams
# __all__ = ["__version__", "process_data", "ActionConfig", "PersonEnrichmentParams", "WebSearchParams"]

__all__ = ["__version__"]
