# SPDX-FileCopyrightText: 2024 Adam Twardoch <adam+github@twardoch.com>
#
# SPDX-License-Identifier: MIT

"""
LLM integration for twat.
"""

from __future__ import annotations

try:
    from twat_llm.__version__ import __version__
except ImportError:
    # Package not installed, or __version__.py not generated by hatch-vcs
    # This is a fallback for development mode when running from source
    # without a proper build/install that generates __version__.py.
    # It's also useful if someone copies the source code without build metadata.
    __version__ = "0.0.0.dev0+unknown"  # Placeholder version

# Expose main functionalities for the library user
from twat_llm.twat_llm import (
    ActionConfig,
    ApiKeySettings,
    PersonEnrichmentParams,
    WebSearchParams,
    process_data,
)
from twat_llm.mallmo import (
    ask,
    ask_batch,
    ask_chain,
    LLMError,
    MediaProcessingError,
    ModelInvocationError,
    BatchProcessingError,
)

__all__ = [
    "ActionConfig",
    "ApiKeySettings",
    "BatchProcessingError",
    "LLMError",
    "MediaProcessingError",
    "ModelInvocationError",
    "PersonEnrichmentParams",
    "WebSearchParams",
    "__version__",
    "ask",
    "ask_batch",
    "ask_chain",
    "process_data",
]
